version: 2

models:

  - name: dim_weather_stations
    columns:
      - name: station_id
        tests:
          - unique
          - not_null

  - name: fct_weather_observations
    columns:
      - name: station_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_weather_stations')
                field: station_id

      - name: observation_time
        tests:
          - not_null